import { SupabaseClient } from "@supabase/supabase-js";

export async function reconcileRawMaterialStock(
  supabase: any,
  businessId: string,
  targetMaterialTypeId?: string
): Promise<{ success: boolean; message: string; updatedCount: number }> {
  if (!businessId) {
    return { success: false, message: "Business ID missing", updatedCount: 0 };
  }

  // 1. Fetch real godowns for this business
  const { data: godowns, error: gError } = await supabase
    .from("godowns")
    .select("id, name")
    .eq("business_id", businessId)
    .is("deleted_at", null);

  if (gError) {
    console.error("[reconcileRawMaterialStock] Error fetching godowns:", gError);
  }

  const defaultGodownId = godowns && godowns.length > 0 ? godowns[0].id : null;

  // 2. Fetch raw material types (all active or specific single material)
  let matQuery = supabase
    .from("raw_material_types")
    .select("id, name, unit, category, reorder_level")
    .eq("business_id", businessId)
    .is("deleted_at", null);

  if (targetMaterialTypeId) {
    matQuery = matQuery.eq("id", targetMaterialTypeId);
  }

  const { data: rawMaterialTypes, error: mError } = await matQuery;

  if (mError || !rawMaterialTypes || rawMaterialTypes.length === 0) {
    return { success: true, message: "No active raw material types found", updatedCount: 0 };
  }

  // Fetch all parent purchases for this business to ensure complete godown & status mapping
  const { data: rawPurchases } = await supabase
    .from("raw_material_purchases")
    .select("id, godown_id, status")
    .eq("business_id", businessId)
    .is("deleted_at", null);
  const purchaseDict = new Map<string, any>((rawPurchases || []).map((p: any) => [p.id, p]));

  // Fetch all manual stock entry vouchers (strictly exclude auto-generated entries)
  const { data: allStockEntries } = await supabase
    .from("raw_material_stock_entries")
    .select("id, godown_id, entry_type, reference_type, reference_id, reference_no, stock_entry_number, remarks, status")
    .eq("business_id", businessId)
    .is("deleted_at", null);

  const manualEntryMap = new Map<string, { godown_id: string; entry_type: string }>();
  (allStockEntries || []).forEach((se: any) => {
    if (se.status === "cancelled") return;

    const refType = (se.reference_type || "").toLowerCase().trim();
    const entryNum = (se.stock_entry_number || "").toUpperCase().trim();
    const remarks = (se.remarks || "").toLowerCase().trim();

    const isAutoGenerated =
      !!se.reference_id ||
      refType === "purchase" ||
      refType === "purchase_invoice" ||
      refType === "return" ||
      refType === "purchase_return" ||
      refType === "production" ||
      refType === "production_lot" ||
      refType === "lot" ||
      refType === "transfer" ||
      refType === "sale" ||
      entryNum.startsWith("STK-IN-PUR-") ||
      entryNum.startsWith("STK-IN-") ||
      entryNum.startsWith("STK-OUT-LOT-") ||
      entryNum.startsWith("STK-OUT-ACC-") ||
      entryNum.startsWith("STK-TRF-") ||
      entryNum.startsWith("STK-OUT-RET-") ||
      remarks.includes("auto-registered") ||
      remarks.includes("auto-generated") ||
      remarks.includes("purchase bill") ||
      remarks.includes("purchase return") ||
      remarks.includes("production lot") ||
      remarks.includes("transfer");

    if (!isAutoGenerated) {
      manualEntryMap.set(se.id, {
        godown_id: se.godown_id || defaultGodownId,
        entry_type: se.entry_type,
      });
    }
  });

  // Fetch all transfers
  const { data: rawTransfers } = await supabase
    .from("raw_material_transfers")
    .select("id, from_godown_id, to_godown_id, status")
    .eq("business_id", businessId)
    .is("deleted_at", null);
  const validTransfers = (rawTransfers || []).filter((t: any) => t.status !== "cancelled");
  const transferDict = new Map<string, any>(validTransfers.map((t: any) => [t.id, t]));

  let updatedCount = 0;

  for (const mat of rawMaterialTypes) {
    // A. Fetch purchase items for this material
    const { data: pItems } = await supabase
      .from("raw_material_purchase_items")
      .select("id, purchase_id, quantity, rate, amount, taxable_value, purchase:raw_material_purchases(id, godown_id, status)")
      .eq("material_type_id", mat.id)
      .eq("business_id", businessId);

    const validPItems = (pItems || []).filter((pi: any) => {
      const p = pi.purchase || purchaseDict.get(pi.purchase_id);
      return p && p.status !== "cancelled";
    });
    const pItemIds = validPItems.map((pi: any) => pi.id);

    const pItemGodownMap = new Map<string, { godownId: string; rate: number }>();
    validPItems.forEach((pi: any) => {
      const p = pi.purchase || purchaseDict.get(pi.purchase_id);
      const gId = p?.godown_id || defaultGodownId;
      if (gId) {
        pItemGodownMap.set(pi.id, { godownId: gId, rate: Number(pi.rate || 0) });
      }
    });

    // B. Fetch rolls for purchase items
    let rolls: any[] = [];
    if (pItemIds.length > 0) {
      const { data: rawRolls } = await supabase
        .from("purchase_rolls")
        .select("*")
        .eq("business_id", businessId)
        .in("purchase_item_id", pItemIds);
      // Filter out cancelled rolls if status column exists
      rolls = (rawRolls || []).filter((r: any) => r.status !== "cancelled");
    }

    // Map to accumulate stock per godown
    const godownStockMap = new Map<string, { currentStock: number; totalValue: number; totalCostSum: number; costCount: number }>();

    if (rolls.length > 0) {
      // Fetch active lot allocations for these rolls
      const rollIds = rolls.map((r: any) => r.id);
      const { data: rawLotRolls } = await supabase
        .from("lot_rolls")
        .select("purchase_roll_id, allocated_meters, lot:production_lots(status)")
        .in("purchase_roll_id", rollIds);

      // Query sale_rolls joined with sale_bill_items and sale_bills
      const { data: rawSaleRolls } = await supabase
        .from("sale_rolls")
        .select("purchase_roll_id, meters, sale_item:sale_bill_items(id, bill:sale_bills(status, deleted_at, is_temporary))")
        .in("purchase_roll_id", rollIds);

      // Fallback check on direct sale_bill_items for legacy records
      const { data: rawSaleItems } = await supabase
        .from("sale_bill_items")
        .select("purchase_roll_id, quantity, bill:sale_bills(status, deleted_at, is_temporary)")
        .in("purchase_roll_id", rollIds);

      // Query purchase_return_rolls joined with purchase_return_items and purchase_returns
      const { data: rawReturnRolls } = await supabase
        .from("purchase_return_rolls")
        .select("purchase_roll_id, returned_meters, return_item:purchase_return_items(id, purchase_return:purchase_returns(status, deleted_at))")
        .in("purchase_roll_id", rollIds);

      // Roll-based materials: Stock per godown is exact sum of audited purchase_rolls.remaining_meters
      for (const r of rolls) {
        const info = pItemGodownMap.get(r.purchase_item_id);
        const gId = info?.godownId || defaultGodownId;
        const rate = info?.rate || 0;
        if (!gId) continue;

        const totalAllocated = (rawLotRolls || [])
          .filter((lr: any) => lr.purchase_roll_id === r.id && lr.lot?.status !== "cancelled")
          .reduce((sum: number, lr: any) => sum + Number(lr.allocated_meters || 0), 0);

        const soldFromSaleRolls = (rawSaleRolls || [])
          .filter((sr: any) => {
            if (sr.purchase_roll_id !== r.id) return false;
            const b = (sr.sale_item as any)?.bill;
            return b && b.status !== "cancelled" && !b.deleted_at && !b.is_temporary;
          })
          .reduce((sum: number, sr: any) => sum + Number(sr.meters || 0), 0);

        const soldFromDirectItems = (rawSaleItems || [])
          .filter((sbi: any) => {
            if (sbi.purchase_roll_id !== r.id) return false;
            const b = (sbi as any)?.bill;
            return b && b.status !== "cancelled" && !b.deleted_at && !b.is_temporary;
          })
          .reduce((sum: number, sbi: any) => sum + Number(sbi.quantity || 0), 0);

        const totalSold = soldFromSaleRolls > 0 ? soldFromSaleRolls : soldFromDirectItems;

        const totalReturned = (rawReturnRolls || [])
          .filter((rr: any) => {
            if (rr.purchase_roll_id !== r.id) return false;
            const pr = (rr.return_item as any)?.purchase_return;
            return pr && pr.status !== "cancelled" && !pr.deleted_at;
          })
          .reduce((sum: number, rr: any) => sum + Number(rr.returned_meters || 0), 0);

        const initialMeters = Number(r.meters || 0);
        const auditedRemaining = Math.max(0, initialMeters - totalAllocated - totalSold - totalReturned);

        // Self-heal database record if out of sync
        if (Number(r.remaining_meters) !== auditedRemaining) {
          await supabase
            .from("purchase_rolls")
            .update({ remaining_meters: auditedRemaining })
            .eq("id", r.id);
        }

        const val = auditedRemaining * rate;

        const existing = godownStockMap.get(gId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
        existing.currentStock += auditedRemaining;
        existing.totalValue += val;
        if (rate > 0) {
          existing.totalCostSum += rate;
          existing.costCount += 1;
        }
        godownStockMap.set(gId, existing);
      }
    } else {
      // Non-roll materials: Sum of Purchased Qty
      validPItems.forEach((pi: any) => {
        const p = pi.purchase || purchaseDict.get(pi.purchase_id);
        const gId = p?.godown_id || defaultGodownId;
        const rate = Number(pi.rate || 0);
        const qty = Number(pi.quantity || 0);
        const taxableVal = Number(pi.taxable_value || (qty * rate));
        if (!gId) return;

        const existing = godownStockMap.get(gId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
        existing.currentStock += qty;
        existing.totalValue += taxableVal;
        if (rate > 0) {
          existing.totalCostSum += rate;
          existing.costCount += 1;
        }
        godownStockMap.set(gId, existing);
      });

      // Deduct purchase returns for non-roll materials
      const { data: returnItems } = await supabase
        .from("purchase_return_items")
        .select("id, return_id, returned_qty, rate, taxable_value, purchase_return:purchase_returns(godown_id, purchase_id, status)")
        .eq("material_type_id", mat.id)
        .eq("business_id", businessId);

      const { data: rawReturns } = await supabase
        .from("purchase_returns")
        .select("id, godown_id, purchase_id, status")
        .eq("business_id", businessId);
      const returnDict = new Map<string, any>((rawReturns || []).map((r: any) => [r.id, r]));

      for (const retItem of returnItems || []) {
        const parentRet = retItem.purchase_return || returnDict.get(retItem.return_id);
        if (parentRet?.status === "cancelled") continue;
        let gId = parentRet?.godown_id;
        if (!gId && parentRet?.purchase_id) {
          const parentP = purchaseDict.get(parentRet.purchase_id);
          gId = parentP?.godown_id;
        }
        gId = gId || defaultGodownId;
        if (!gId) continue;

        const retQty = Number(retItem.returned_qty || 0);
        const retRate = Number(retItem.rate || 0);
        const retTaxableVal = Number(retItem.taxable_value || (retQty * retRate));

        const existing = godownStockMap.get(gId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
        existing.currentStock = Math.max(0, existing.currentStock - retQty);
        existing.totalValue = Math.max(0, existing.totalValue - retTaxableVal);
        godownStockMap.set(gId, existing);
      }

      // Deduct accessory allocations from production lots
      if (pItemIds.length > 0) {
        const { data: lotAccessories } = await supabase
          .from("production_lot_accessories")
          .select("purchase_item_id, allocated_qty, godown_id, unit_rate, lot:production_lots(status)")
          .in("purchase_item_id", pItemIds);

        (lotAccessories || []).forEach((la: any) => {
          if (la.lot?.status === "cancelled") return;
          const info = pItemGodownMap.get(la.purchase_item_id);
          const gId = la.godown_id || info?.godownId || defaultGodownId;
          const rate = Number(la.unit_rate || info?.rate || 0);
          const allocQty = Number(la.allocated_qty || 0);
          if (!gId || allocQty <= 0) return;

          const existing = godownStockMap.get(gId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
          existing.currentStock = Math.max(0, existing.currentStock - allocQty);
          existing.totalValue = Math.max(0, existing.totalValue - (allocQty * rate));
          godownStockMap.set(gId, existing);
        });
      }

      // Deduct accessory sales from sale bills
      const { data: rawDirectSales } = await supabase
        .from("sale_bill_items")
        .select("material_type_id, quantity, rate, amount, bill:sale_bills(godown_id, status, deleted_at, is_temporary)")
        .eq("material_type_id", mat.id)
        .eq("business_id", businessId);

      (rawDirectSales || []).forEach((sbi: any) => {
        const b = sbi.bill;
        if (!b || b.status === "cancelled" || b.deleted_at || b.is_temporary) return;
        const gId = b.godown_id || defaultGodownId;
        const soldQty = Number(sbi.quantity || 0);
        const rate = Number(sbi.rate || 0);
        const val = Number(sbi.amount || (soldQty * rate));
        if (!gId || soldQty <= 0) return;

        const existing = godownStockMap.get(gId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
        existing.currentStock = Math.max(0, existing.currentStock - soldQty);
        existing.totalValue = Math.max(0, existing.totalValue - val);
        godownStockMap.set(gId, existing);
      });
    }

    // C. Adjust transfers for this material
    if (transferDict.size > 0) {
      const transferIds = Array.from(transferDict.keys());
      const { data: transferItems } = await supabase
        .from("raw_material_transfer_items")
        .select("transfer_id, material_type_id, quantity, unit_cost, total_value")
        .eq("material_type_id", mat.id)
        .eq("business_id", businessId)
        .in("transfer_id", transferIds);

      (transferItems || []).forEach((ti: any) => {
        const parentT = transferDict.get(ti.transfer_id);
        if (!parentT) return;
        const fromGId = parentT.from_godown_id;
        const toGId = parentT.to_godown_id;
        const qty = Number(ti.quantity || 0);
        const val = Number(ti.total_value || (qty * Number(ti.unit_cost || 0)));

        // Deduct from source godown
        if (fromGId) {
          const existingFrom = godownStockMap.get(fromGId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
          existingFrom.currentStock = Math.max(0, existingFrom.currentStock - qty);
          existingFrom.totalValue = Math.max(0, existingFrom.totalValue - val);
          godownStockMap.set(fromGId, existingFrom);
        }

        // If transfer is completed, add to destination godown
        if (toGId && parentT.status === "completed") {
          const existingTo = godownStockMap.get(toGId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
          existingTo.currentStock += qty;
          existingTo.totalValue += val;
          godownStockMap.set(toGId, existingTo);
        }
      });
    }

    // D. Add/Deduct genuine manual stock adjustments (`raw_material_stock_entries`)
    // Auto-generated vouchers are already accounted for above and excluded from manualEntryMap.
    if (manualEntryMap.size > 0) {
      const manualEntryIds = Array.from(manualEntryMap.keys());
      const { data: stockEntryItems } = await supabase
        .from("raw_material_stock_entry_items")
        .select("id, stock_entry_id, quantity, rate, amount")
        .eq("material_type_id", mat.id)
        .eq("business_id", businessId)
        .in("stock_entry_id", manualEntryIds);

      (stockEntryItems || []).forEach((sei: any) => {
        const seInfo = manualEntryMap.get(sei.stock_entry_id);
        if (!seInfo) return;
        const gId = seInfo.godown_id || defaultGodownId;
        const type = seInfo.entry_type;
        const qty = Number(sei.quantity || 0);
        const rate = Number(sei.rate || 0);
        const val = Number(sei.amount || (qty * rate));
        if (!gId) return;

        const existing = godownStockMap.get(gId) || { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 };
        if (type === "stock_in") {
          existing.currentStock += qty;
          existing.totalValue += val;
        } else if (type === "stock_out" || type === "issue" || type === "damage") {
          existing.currentStock = Math.max(0, existing.currentStock - qty);
          existing.totalValue = Math.max(0, existing.totalValue - val);
        }
        godownStockMap.set(gId, existing);
      });
    }

    if (godownStockMap.size === 0 && defaultGodownId) {
      godownStockMap.set(defaultGodownId, { currentStock: 0, totalValue: 0, totalCostSum: 0, costCount: 0 });
    }

    // E. Synchronize `raw_material_current_stock` table
    for (const [gId, stockData] of Array.from(godownStockMap.entries())) {
      const finalQty = Math.max(0, Number(stockData.currentStock.toFixed(2)));
      const finalValue = Math.max(0, Number(stockData.totalValue.toFixed(2)));
      const avgCost = finalQty > 0
        ? Number((finalValue / finalQty).toFixed(2))
        : (stockData.costCount > 0 ? Number((stockData.totalCostSum / stockData.costCount).toFixed(2)) : 0);

      const { data: existingRows } = await supabase
        .from("raw_material_current_stock")
        .select("id")
        .eq("business_id", businessId)
        .eq("material_type_id", mat.id)
        .eq("godown_id", gId);

      if (existingRows && existingRows.length > 0) {
        const primaryId = existingRows[0].id;
        await supabase
          .from("raw_material_current_stock")
          .update({
            current_stock: finalQty,
            unit_cost: avgCost,
            stock_value: finalValue,
            last_updated_at: new Date().toISOString(),
          })
          .eq("id", primaryId);

        // Delete duplicate records if any exist
        if (existingRows.length > 1) {
          const extraIds = existingRows.slice(1).map((r: any) => r.id);
          await supabase.from("raw_material_current_stock").delete().in("id", extraIds);
        }
      } else {
        await supabase
          .from("raw_material_current_stock")
          .insert({
            business_id: businessId,
            material_type_id: mat.id,
            godown_id: gId,
            current_stock: finalQty,
            unit_cost: avgCost,
            stock_value: finalValue,
            last_updated_at: new Date().toISOString(),
          });
      }
      updatedCount++;
    }

    // Zero out any other godowns for this material that have no stock
    const { data: allExistingForMat } = await supabase
      .from("raw_material_current_stock")
      .select("id, godown_id, current_stock")
      .eq("business_id", businessId)
      .eq("material_type_id", mat.id);

    const activeGIds = new Set(godownStockMap.keys());
    for (const row of allExistingForMat || []) {
      if (!activeGIds.has(row.godown_id) && Number(row.current_stock || 0) !== 0) {
        await supabase
          .from("raw_material_current_stock")
          .update({
            current_stock: 0,
            stock_value: 0,
            last_updated_at: new Date().toISOString(),
          })
          .eq("id", row.id);
      }
    }
  }

  return {
    success: true,
    message: "Ground-truth inventory reconciliation completed successfully",
    updatedCount,
  };
}
