-- SQL Patch: Add GST calculation columns to purchase_returns, purchase_return_items, sales_returns, and sales_return_items

ALTER TABLE IF EXISTS purchase_returns 
ADD COLUMN IF NOT EXISTS total_taxable_value NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cgst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS sgst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS igst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS round_off NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst_type TEXT DEFAULT 'with_gst';

ALTER TABLE IF EXISTS purchase_return_items 
ADD COLUMN IF NOT EXISTS gst_percent NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0;

ALTER TABLE IF EXISTS sales_returns 
ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS cgst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS sgst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS igst NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS round_off NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst_type TEXT DEFAULT 'with_gst';

CREATE TABLE IF NOT EXISTS sales_return_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  business_id UUID NOT NULL,
  return_id UUID NOT NULL REFERENCES sales_returns(id) ON DELETE CASCADE,
  sale_item_id UUID,
  design_id UUID,
  colour_id UUID,
  size TEXT,
  size_quantities JSONB DEFAULT '{}'::jsonb,
  unit_rate NUMERIC DEFAULT 0,
  returned_qty NUMERIC DEFAULT 0,
  taxable_amount NUMERIC DEFAULT 0,
  gst_percent NUMERIC DEFAULT 0,
  gst_amount NUMERIC DEFAULT 0,
  amount NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS sales_return_items 
ADD COLUMN IF NOT EXISTS taxable_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst_percent NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS gst_amount NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0;
